services:
  db:
    image: postgres
    restart: always
    ports: 
      - 15432:5432
    volumes:
      - ./dbs/postgres-data:/var/lib/postgresql/data
    env_file:
      - db.env
  
  auth:
    image: express-auth-backend
    build:
      context: ./auth
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/www/apps/auth/node_modules
    env_file:
      - ./auth/.env.prod
    depends_on:
      - db

  queue:
    image: express-queue-backend
    build:
      context: ./queue
    restart: always
    ports:
      - 8001:8001
    volumes:
      - /var/www/apps/queue/node_modules
    env_file:
      - ./queue/.env.prod
    depends_on:
      - db

  student:
    image: express-student-backend
    build:
      context: ./student
    restart: always
    ports:
      - 8002:8002
    volumes:
      - /var/www/apps/student/node_modules
    env_file:
      - ./student/.env.prod
    depends_on:
      - db
